#pragma once


enum class ReadRegType
{
    STATUS,
    PARAM,
};

enum class ReadMethod
{
    NORMAL,
};

enum class WriteRegType
{
    PARAM,
    PARAM_VOLATILE,
    CONTROL,
};

enum class WriteMethod
{
    NORMAL,
    NO_REPLY,
    BROADCAST
};

enum class CanFuncionCodeType{
    UNKNOWN_FUNCTION_CODE = 0,
    READ_STATUS = 1,
    READ_PARAM = 2,
    WRITE_PARAM = 3,
    WRITE_COMMAND = 4,
    WRITE_SPECIAL = 6,
    WRITE_REPLYLESS = 8,
    WRITE_SPECIAL_REPLYLESS = 9,
    WRITE_PARAM_BROADCAST = 10,
    WRITE_COMMAND_BROADCAST = 11,
    WRITE_SPECIAL_BROADCAST = 12,
    REPORT_STATUS = 20,
    REPORT_FAULT = 21,
};

enum class ReplyOffset{
    REQUEST = 0x00,
    REPLY_NORMAL ,
    REPLY_ERROR,
    REQUEST_DUAL,
    REPLY_DUAL_NORMAL,
    REPLY_DUAL_ERROR,
    REQUEST_NOSAVE,
    REPLY_NOSAVE_NORMAL,
    REPLY_NOSAVE_ERROR,
};

enum class CanFuncionCode{

ERROR_REPLY_ILLEGAL_FUNCTION_REQUEST       = 0x00,

READ_SINGLE_STATUS                 = 0x0A,
NORMAL_REPLY_READ_SINGLE_STATUS = 0x0B,
ERROR_REPLY_READ_SINGLE_STATUS = 0x0C,

READ_TWO_STATUS = 0x0D,
NORMAL_REPLY_READ_TWO_STATUS = 0x0E,
ERROR_REPLY_READ_TWO_STATUS = 0x0F,

READ_SINGLE_PARAMETER = 0x14,
NORMAL_REPLY_READ_SINGLE_PARAMETER = 0x15,
ERROR_REPLY_READ_SINGLE_PARAMETER = 0x16,

READ_TWO_PARAMETER = 0x17,
NORMAL_REPLY_READ_TWO_PARAMETER = 0x18,
ERROR_REPLY_READ_TWO_PARAMETER = 0x19,

WRITE_SINGLE_PARAMETER = 0x1E,
NORMAL_REPLY_WRITE_SINGLE_PARAMETER = 0x1F,
ERROR_REPLY_WRITE_SINGLE_PARAMETER = 0x20,

WRITE_TWO_PARAMETER = 0x21,
NORMAL_REPLY_WRITE_TWO_PARAMETER = 0x22,
ERROR_REPLY_WRITE_TWO_PARAMETER = 0x23,

WRITE_SINGLE_VOLATILE_PARAMETER = 0x24,
NORMAL_REPLY_WRITE_SINGLE_VOLATILE_PARAMETER = 0x25,
ERROR_REPLY_WRITE_SINGLE_VOLATILE_PARAMETER = 0x26,

WRITE_SINGLE_COMMAND = 0x28,
NORMAL_REPLY_WRITE_SINGLE_COMMAND = 0x29,
ERROR_REPLY_WRITE_SINGLE_COMMAND = 0x2A,

WRITE_TWO_COMMAND = 0x2B,
NORMAL_REPLY_WRITE_TWO_COMMAND = 0x2C,
ERROR_REPLY_WRITE_TWO_COMMAND = 0x2D,

WRITE_SPECIAL = 0x3C,
NORMAL_REPLY_WRITE_SPECIAL = 0x3D,
ERROR_REPLY_WRITE_SPECIAL = 0x3E,

WRITE_SINGLE_PARAMETER_NO_REPLY = 0x51,
WRITE_SINGLE_VOLATILE_PARAMETER_NO_REPLY = 0x51,
WRITE_TWO_PARAMETER_NO_REPLY = 0x52,
WRITE_TWO_VOLATILE_PARAMETER_NO_REPLY = 0x53,
WRITE_SINGLE_COMMAND_NO_REPLY = 0x54,
WRITE_TWO_COMMAND_NO_REPLY = 0x55,

WRITE_SPECIAL__NO_REPLY = 0x5A,

BROADCAST_WRITE_SINGLE_PARAMETER = 0x64,
BROADCAST_WRITE_TWO_PARAMETER = 0x65,
BROADCAST_WRITE_SINGLE_VOLATILE_PARAMETER = 0x66,
BROADCAST_WRITE_SINGLE_COMMAND = 0x6E,
BROADCAST_WRITE_TWO_COMMAND = 0x6F,
BROADCAST_WRITE_SPECIAL = 0x78,

REPORT_TWO_BIT_STATUS = 0xC9,

USER_DEFINED_REPORT_THREE_STATUS_1 = 0xCA,
USER_DEFINED_REPORT_THREE_STATUS_2 = 0xCB,
USER_DEFINED_REPORT_THREE_STATUS_3 = 0xCC,
USER_DEFINED_REPORT_THREE_STATUS_4 = 0xCD,
REPORT_FAULT_INFO = 0xD2
};